In [1]:
import numpy as np
print(np.__version__)

1.14.0


In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
arr = np.ones((3,3), dtype=bool)

In [12]:
arr[1] = False
print(arr)

[[ True  True  True]
 [False False False]
 [ True  True  True]]


In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

In [20]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [35]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [37]:
arr[arr % 2 == 0] = 1
arr

array([ 1, -1,  1, -1,  1, -1,  1, -1,  1, -1])

In [39]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [42]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()
#> False

False